# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\U62658\Documents\PythonProjects\PruebasLocales\Fotogrametry\Utils\DocX_generator\src\gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Naviation_plotter(object):
    def setupUi(self, Naviation_plotter):
        Naviation_plotter.setObjectName("Naviation_plotter")
        Naviation_plotter.resize(891, 834)
        self.centralwidget = QtWidgets.QWidget(Naviation_plotter)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.print_ly = QtWidgets.QVBoxLayout()
        self.print_ly.setObjectName("print_ly")
        self.verticalLayout.addLayout(self.print_ly)
        self.checkpoints_tb = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkpoints_tb.sizePolicy().hasHeightForWidth())
        self.checkpoints_tb.setSizePolicy(sizePolicy)
        self.checkpoints_tb.setShowGrid(False)
        self.checkpoints_tb.setColumnCount(8)
        self.checkpoints_tb.setObjectName("checkpoints_tb")
        self.checkpoints_tb.setRowCount(0)
        self.verticalLayout.addWidget(self.checkpoints_tb)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.import_pb = QtWidgets.QPushButton(self.centralwidget)
        self.import_pb.setObjectName("import_pb")
        self.verticalLayout_4.addWidget(self.import_pb)
        self.view_pb = QtWidgets.QPushButton(self.centralwidget)
        self.view_pb.setObjectName("view_pb")
        self.verticalLayout_4.addWidget(self.view_pb)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scale_sb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.scale_sb.setObjectName("scale_sb")
        self.horizontalLayout_5.addWidget(self.scale_sb)
        self.scale_units_cb = QtWidgets.QComboBox(self.groupBox)
        self.scale_units_cb.setObjectName("scale_units_cb")
        self.horizontalLayout_5.addWidget(self.scale_units_cb)
        self.scale_pb = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_pb.sizePolicy().hasHeightForWidth())
        self.scale_pb.setSizePolicy(sizePolicy)
        self.scale_pb.setObjectName("scale_pb")
        self.horizontalLayout_5.addWidget(self.scale_pb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.north_pb = QtWidgets.QPushButton(self.groupBox)
        self.north_pb.setObjectName("north_pb")
        self.verticalLayout_3.addWidget(self.north_pb)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.speed_sb = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_sb.sizePolicy().hasHeightForWidth())
        self.speed_sb.setSizePolicy(sizePolicy)
        self.speed_sb.setMinimum(1)
        self.speed_sb.setMaximum(999)
        self.speed_sb.setObjectName("speed_sb")
        self.horizontalLayout_6.addWidget(self.speed_sb)
        self.speed_units_cb = QtWidgets.QComboBox(self.groupBox)
        self.speed_units_cb.setObjectName("speed_units_cb")
        self.horizontalLayout_6.addWidget(self.speed_units_cb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.save_config_pb = QtWidgets.QPushButton(self.groupBox)
        self.save_config_pb.setObjectName("save_config_pb")
        self.gridLayout_2.addWidget(self.save_config_pb, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.fuel_sb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.fuel_sb.setObjectName("fuel_sb")
        self.horizontalLayout_8.addWidget(self.fuel_sb)
        self.fuel_units_cb = QtWidgets.QComboBox(self.groupBox)
        self.fuel_units_cb.setObjectName("fuel_units_cb")
        self.horizontalLayout_8.addWidget(self.fuel_units_cb)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lines_width_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.lines_width_sb.setMinimum(1)
        self.lines_width_sb.setMaximum(100)
        self.lines_width_sb.setObjectName("lines_width_sb")
        self.horizontalLayout.addWidget(self.lines_width_sb)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_marker_chb = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_marker_chb.sizePolicy().hasHeightForWidth())
        self.line_marker_chb.setSizePolicy(sizePolicy)
        self.line_marker_chb.setObjectName("line_marker_chb")
        self.horizontalLayout_7.addWidget(self.line_marker_chb)
        self.mins_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.mins_sb.setMinimum(1)
        self.mins_sb.setMaximum(100)
        self.mins_sb.setProperty("value", 2)
        self.mins_sb.setObjectName("mins_sb")
        self.horizontalLayout_7.addWidget(self.mins_sb)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.info_box_chb = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_box_chb.sizePolicy().hasHeightForWidth())
        self.info_box_chb.setSizePolicy(sizePolicy)
        self.info_box_chb.setObjectName("info_box_chb")
        self.gridLayout_3.addWidget(self.info_box_chb, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lines_color_cb = QtWidgets.QComboBox(self.groupBox_2)
        self.lines_color_cb.setObjectName("lines_color_cb")
        self.horizontalLayout_2.addWidget(self.lines_color_cb)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.text_size_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.text_size_sb.setMinimum(10)
        self.text_size_sb.setMaximum(1000)
        self.text_size_sb.setObjectName("text_size_sb")
        self.horizontalLayout_3.addWidget(self.text_size_sb)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.start_stop_pb = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_stop_pb.sizePolicy().hasHeightForWidth())
        self.start_stop_pb.setSizePolicy(sizePolicy)
        self.start_stop_pb.setObjectName("start_stop_pb")
        self.verticalLayout_4.addWidget(self.start_stop_pb)
        self.reset_pb = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pb.sizePolicy().hasHeightForWidth())
        self.reset_pb.setSizePolicy(sizePolicy)
        self.reset_pb.setObjectName("reset_pb")
        self.verticalLayout_4.addWidget(self.reset_pb)
        self.save_pb = QtWidgets.QPushButton(self.centralwidget)
        self.save_pb.setObjectName("save_pb")
        self.verticalLayout_4.addWidget(self.save_pb)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        Naviation_plotter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Naviation_plotter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 21))
        self.menubar.setObjectName("menubar")
        Naviation_plotter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Naviation_plotter)
        self.statusbar.setObjectName("statusbar")
        Naviation_plotter.setStatusBar(self.statusbar)

        self.retranslateUi(Naviation_plotter)
        QtCore.QMetaObject.connectSlotsByName(Naviation_plotter)

    def retranslateUi(self, Naviation_plotter):
        _translate = QtCore.QCoreApplication.translate
        Naviation_plotter.setWindowTitle(_translate("Naviation_plotter", "Navigation Plotter"))
        self.import_pb.setText(_translate("Naviation_plotter", "Open map"))
        self.view_pb.setText(_translate("Naviation_plotter", "Set current view as default"))
        self.groupBox.setTitle(_translate("Naviation_plotter", "Configuration"))
        self.scale_pb.setText(_translate("Naviation_plotter", "Set scale"))
        self.north_pb.setText(_translate("Naviation_plotter", "Set north direction"))
        self.label.setText(_translate("Naviation_plotter", "Cruise speed"))
        self.save_config_pb.setText(_translate("Naviation_plotter", "Save configuration"))
        self.label_3.setText(_translate("Naviation_plotter", "Fuel consumption"))
        self.groupBox_2.setTitle(_translate("Naviation_plotter", "Display options"))
        self.label_4.setText(_translate("Naviation_plotter", "Lines width"))
        self.line_marker_chb.setText(_translate("Naviation_plotter", "Show line mark each"))
        self.label_2.setText(_translate("Naviation_plotter", "mins"))
        self.info_box_chb.setText(_translate("Naviation_plotter", "Show info box"))
        self.label_5.setText(_translate("Naviation_plotter", "Lines color"))
        self.label_6.setText(_translate("Naviation_plotter", "Text size"))
        self.start_stop_pb.setText(_translate("Naviation_plotter", "Start"))
        self.reset_pb.setText(_translate("Naviation_plotter", "Reset"))
        self.save_pb.setText(_translate("Naviation_plotter", "Save"))